#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#==========================
#  Name:        TagSelector
#  Author:      llk2why; and kahsolt fucked it up
#  Time:        2017/04/16
#  Desciption:  Tag Selector in manual mode

import sys, os
from PyQt4.QtCore import *
from PyQt4.QtGui import *
from PyQt4 import phonon

try:
    _fromUtf8 = QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s
try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

# Functions
def _String2Utf8(s):
    return s.encode('utf8')
def QString2String(qStr):
    return unicode(qStr.toUtf8(), 'utf-8', 'ignore')

class TagSelector(QDialog):
    def __init__(self, parent = None):
        super(TagSelector, self).__init__()

        # 绘制UI界面
        self.UI = UI_TagSelector()
        self.UI.setupUi(self)

        # 绑定UI Widgets事件
        self.UI.btn_tagOK.clicked.connect(self.btn_tagOK_click)

        self.addCheckBox()
        self.tagsSelected = []

    def addCheckBox(self):
        self.checkBoxSet = []
        self.checkBoxSet.append(self.UI.checkBox)
        self.checkBoxSet.append(self.UI.checkBox2)
        self.checkBoxSet.append(self.UI.checkBox3)
        self.checkBoxSet.append(self.UI.checkBox4)
        self.checkBoxSet.append(self.UI.checkBox5)
        self.checkBoxSet.append(self.UI.checkBox6)
        self.checkBoxSet.append(self.UI.checkBox7)
        self.checkBoxSet.append(self.UI.checkBox8)
        self.checkBoxSet.append(self.UI.checkBox9)
        self.checkBoxSet.append(self.UI.checkBox10)
        self.checkBoxSet.append(self.UI.checkBox11)
        self.checkBoxSet.append(self.UI.checkBox12)
        self.checkBoxSet.append(self.UI.checkBox13)
        self.checkBoxSet.append(self.UI.checkBox14)
        self.checkBoxSet.append(self.UI.checkBox15)
        self.checkBoxSet.append(self.UI.checkBox16)
        self.checkBoxSet.append(self.UI.checkBox17)
        self.checkBoxSet.append(self.UI.checkBox18)
        self.checkBoxSet.append(self.UI.checkBox19)
        self.checkBoxSet.append(self.UI.checkBox20)
        self.checkBoxSet.append(self.UI.checkBox21)
        self.checkBoxSet.append(self.UI.checkBox22)
        self.checkBoxSet.append(self.UI.checkBox23)
        self.checkBoxSet.append(self.UI.checkBox24)
        self.checkBoxSet.append(self.UI.checkBox25)
        self.checkBoxSet.append(self.UI.checkBox26)
        self.checkBoxSet.append(self.UI.checkBox27)
        self.checkBoxSet.append(self.UI.checkBox28)
        self.checkBoxSet.append(self.UI.checkBox29)
        self.checkBoxSet.append(self.UI.checkBox30)
        self.checkBoxSet.append(self.UI.checkBox31)
        self.checkBoxSet.append(self.UI.checkBox32)
        self.checkBoxSet.append(self.UI.checkBox33)
        self.checkBoxSet.append(self.UI.checkBox34)
        self.checkBoxSet.append(self.UI.checkBox35)
        self.checkBoxSet.append(self.UI.checkBox36)

    def btn_tagOK_click(self):
        self.tagsSelected = []
        for chkbox in self.checkBoxSet:
            if chkbox.isChecked() == True:
                self.tagsSelected.append(_String2Utf8(QString2String(chkbox.text())))
        self.hide()

class UI_TagSelector(object):
    def setupUi(self, parent):
        self.groupBox = QGroupBox(parent)
        self.groupBox.setGeometry(QRect(10, 10, 121, 261))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QRect(10, 20, 101, 229))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkBox = QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox2 = QCheckBox(self.layoutWidget)
        self.checkBox2.setObjectName(_fromUtf8("checkBox2"))
        self.verticalLayout.addWidget(self.checkBox2)
        self.checkBox3 = QCheckBox(self.layoutWidget)
        self.checkBox3.setObjectName(_fromUtf8("checkBox3"))
        self.verticalLayout.addWidget(self.checkBox3)
        self.checkBox4 = QCheckBox(self.layoutWidget)
        self.checkBox4.setObjectName(_fromUtf8("checkBox4"))
        self.verticalLayout.addWidget(self.checkBox4)
        self.checkBox5 = QCheckBox(self.layoutWidget)
        self.checkBox5.setObjectName(_fromUtf8("checkBox5"))
        self.verticalLayout.addWidget(self.checkBox5)
        self.checkBox6 = QCheckBox(self.layoutWidget)
        self.checkBox6.setObjectName(_fromUtf8("checkBox6"))
        self.verticalLayout.addWidget(self.checkBox6)
        self.checkBox7 = QCheckBox(self.layoutWidget)
        self.checkBox7.setObjectName(_fromUtf8("checkBox7"))
        self.verticalLayout.addWidget(self.checkBox7)
        self.checkBox8 = QCheckBox(self.layoutWidget)
        self.checkBox8.setObjectName(_fromUtf8("checkBox8"))
        self.verticalLayout.addWidget(self.checkBox8)
        self.checkBox9 = QCheckBox(self.layoutWidget)
        self.checkBox9.setObjectName(_fromUtf8("checkBox9"))
        self.verticalLayout.addWidget(self.checkBox9)
        self.groupBox_2 = QGroupBox(parent)
        self.groupBox_2.setGeometry(QRect(20, 270, 121, 131))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget1 = QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QRect(0, 20, 101, 99))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBox10 = QCheckBox(self.layoutWidget1)
        self.checkBox10.setObjectName(_fromUtf8("checkBox10"))
        self.verticalLayout_2.addWidget(self.checkBox10)
        self.checkBox11 = QCheckBox(self.layoutWidget1)
        self.checkBox11.setObjectName(_fromUtf8("checkBox11"))
        self.verticalLayout_2.addWidget(self.checkBox11)
        self.checkBox12 = QCheckBox(self.layoutWidget1)
        self.checkBox12.setObjectName(_fromUtf8("checkBox12"))
        self.verticalLayout_2.addWidget(self.checkBox12)
        self.checkBox13 = QCheckBox(self.layoutWidget1)
        self.checkBox13.setObjectName(_fromUtf8("checkBox13"))
        self.verticalLayout_2.addWidget(self.checkBox13)
        self.groupBox_3 = QGroupBox(parent)
        self.groupBox_3.setGeometry(QRect(140, 160, 141, 291))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget2 = QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QRect(10, 30, 101, 241))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox18 = QCheckBox(self.layoutWidget2)
        self.checkBox18.setObjectName(_fromUtf8("checkBox18"))
        self.verticalLayout_3.addWidget(self.checkBox18)
        self.checkBox19 = QCheckBox(self.layoutWidget2)
        self.checkBox19.setObjectName(_fromUtf8("checkBox19"))
        self.verticalLayout_3.addWidget(self.checkBox19)
        self.checkBox20 = QCheckBox(self.layoutWidget2)
        self.checkBox20.setObjectName(_fromUtf8("checkBox20"))
        self.verticalLayout_3.addWidget(self.checkBox20)
        self.checkBox21 = QCheckBox(self.layoutWidget2)
        self.checkBox21.setObjectName(_fromUtf8("checkBox21"))
        self.verticalLayout_3.addWidget(self.checkBox21)
        self.checkBox22 = QCheckBox(self.layoutWidget2)
        self.checkBox22.setObjectName(_fromUtf8("checkBox22"))
        self.verticalLayout_3.addWidget(self.checkBox22)
        self.checkBox23 = QCheckBox(self.layoutWidget2)
        self.checkBox23.setObjectName(_fromUtf8("checkBox23"))
        self.verticalLayout_3.addWidget(self.checkBox23)
        self.checkBox24 = QCheckBox(self.layoutWidget2)
        self.checkBox24.setObjectName(_fromUtf8("checkBox24"))
        self.verticalLayout_3.addWidget(self.checkBox24)
        self.checkBox25 = QCheckBox(self.layoutWidget2)
        self.checkBox25.setObjectName(_fromUtf8("checkBox25"))
        self.verticalLayout_3.addWidget(self.checkBox25)
        self.checkBox26 = QCheckBox(self.layoutWidget2)
        self.checkBox26.setObjectName(_fromUtf8("checkBox26"))
        self.verticalLayout_3.addWidget(self.checkBox26)
        self.groupBox_4 = QGroupBox(parent)
        self.groupBox_4.setGeometry(QRect(140, 10, 141, 151))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget3 = QWidget(self.groupBox_4)
        self.layoutWidget3.setGeometry(QRect(10, 20, 111, 121))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_4 = QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkBox14 = QCheckBox(self.layoutWidget3)
        self.checkBox14.setObjectName(_fromUtf8("checkBox14"))
        self.verticalLayout_4.addWidget(self.checkBox14)
        self.checkBox15 = QCheckBox(self.layoutWidget3)
        self.checkBox15.setObjectName(_fromUtf8("checkBox15"))
        self.verticalLayout_4.addWidget(self.checkBox15)
        self.checkBox16 = QCheckBox(self.layoutWidget3)
        self.checkBox16.setObjectName(_fromUtf8("checkBox16"))
        self.verticalLayout_4.addWidget(self.checkBox16)
        self.checkBox17 = QCheckBox(self.layoutWidget3)
        self.checkBox17.setObjectName(_fromUtf8("checkBox17"))
        self.verticalLayout_4.addWidget(self.checkBox17)
        self.groupBox_6 = QGroupBox(parent)
        self.groupBox_6.setGeometry(QRect(300, 20, 91, 391))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.layoutWidget4 = QWidget(self.groupBox_6)
        self.layoutWidget4.setGeometry(QRect(0, 40, 91, 341))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_6 = QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.checkBox27 = QCheckBox(self.layoutWidget4)
        self.checkBox27.setObjectName(_fromUtf8("checkBox27"))
        self.verticalLayout_6.addWidget(self.checkBox27)
        self.checkBox28 = QCheckBox(self.layoutWidget4)
        self.checkBox28.setObjectName(_fromUtf8("checkBox28"))
        self.verticalLayout_6.addWidget(self.checkBox28)
        self.checkBox29 = QCheckBox(self.layoutWidget4)
        self.checkBox29.setObjectName(_fromUtf8("checkBox29"))
        self.verticalLayout_6.addWidget(self.checkBox29)
        self.checkBox30 = QCheckBox(self.layoutWidget4)
        self.checkBox30.setObjectName(_fromUtf8("checkBox30"))
        self.verticalLayout_6.addWidget(self.checkBox30)
        self.checkBox31 = QCheckBox(self.layoutWidget4)
        self.checkBox31.setObjectName(_fromUtf8("checkBox31"))
        self.verticalLayout_6.addWidget(self.checkBox31)
        self.checkBox32 = QCheckBox(self.layoutWidget4)
        self.checkBox32.setObjectName(_fromUtf8("checkBox32"))
        self.verticalLayout_6.addWidget(self.checkBox32)
        self.checkBox33 = QCheckBox(self.layoutWidget4)
        self.checkBox33.setObjectName(_fromUtf8("checkBox33"))
        self.verticalLayout_6.addWidget(self.checkBox33)
        self.checkBox34 = QCheckBox(self.layoutWidget4)
        self.checkBox34.setObjectName(_fromUtf8("checkBox34"))
        self.verticalLayout_6.addWidget(self.checkBox34)
        self.checkBox35 = QCheckBox(self.layoutWidget4)
        self.checkBox35.setObjectName(_fromUtf8("checkBox35"))
        self.verticalLayout_6.addWidget(self.checkBox35)
        self.checkBox36 = QCheckBox(self.layoutWidget4)
        self.checkBox36.setObjectName(_fromUtf8("checkBox36"))
        self.verticalLayout_6.addWidget(self.checkBox36)
        self.btn_tagOK = QPushButton(parent)
        self.btn_tagOK.setGeometry(QRect(170, 460, 93, 28))
        self.btn_tagOK.setObjectName(_fromUtf8("btn_tag_ok"))

        self.retranslateUi(parent)
        QMetaObject.connectSlotsByName(parent)

    def retranslateUi(self, parent):
        parent.setWindowTitle(u'配乐标签')
        parent.setWindowIcon(QIcon(r'./icon/SmartBGM.ico'))
        parent.setObjectName(_fromUtf8("UI_TagSelector"))
        parent.resize(414, 505)

        self.groupBox.setTitle(_translate("UI_TagSelector", "风格", None))
        self.checkBox.setText(_translate("UI_TagSelector", "流行摇滚", None))
        self.checkBox2.setText(_translate("UI_TagSelector", "乡村民谣", None))
        self.checkBox3.setText(_translate("UI_TagSelector", "爵士蓝调", None))
        self.checkBox4.setText(_translate("UI_TagSelector", "金属朋克", None))
        self.checkBox5.setText(_translate("UI_TagSelector", "轻音乐", None))
        self.checkBox6.setText(_translate("UI_TagSelector", "古典", None))
        self.checkBox7.setText(_translate("UI_TagSelector", "国风", None))
        self.checkBox8.setText(_translate("UI_TagSelector", "电子", None))
        self.checkBox9.setText(_translate("UI_TagSelector", "说唱", None))

        self.groupBox_2.setTitle(_translate("UI_TagSelector", "场景", None))
        self.checkBox10.setText(_translate("UI_TagSelector", "清晨", None))
        self.checkBox11.setText(_translate("UI_TagSelector", "下午茶", None))
        self.checkBox12.setText(_translate("UI_TagSelector", "夜晚", None))
        self.checkBox13.setText(_translate("UI_TagSelector", "学习工作", None))
        self.checkBox14.setText(_translate("UI_TagSelector", "运动旅行", None))
        self.checkBox15.setText(_translate("UI_TagSelector", "婚礼庆典", None))
        self.checkBox16.setText(_translate("UI_TagSelector", "影视", None))
        self.checkBox17.setText(_translate("UI_TagSelector", "ACG", None))

        self.groupBox_3.setTitle(_translate("UI_TagSelector", "情感", None))
        self.checkBox18.setText(_translate("UI_TagSelector", "清新明媚", None))
        self.checkBox19.setText(_translate("UI_TagSelector", "兴奋动感", None))
        self.checkBox20.setText(_translate("UI_TagSelector", "治愈感动", None))
        self.checkBox21.setText(_translate("UI_TagSelector", "怀旧伤感", None))
        self.checkBox22.setText(_translate("UI_TagSelector", "安静放松", None))
        self.checkBox23.setText(_translate("UI_TagSelector", "快乐", None))
        self.checkBox24.setText(_translate("UI_TagSelector", "浪漫", None))
        self.checkBox25.setText(_translate("UI_TagSelector", "孤独", None))
        self.checkBox26.setText(_translate("UI_TagSelector", "思念", None))

        self.groupBox_6.setTitle(_translate("UI_TagSelector", "乐器", None))
        self.checkBox27.setText(_translate("UI_TagSelector", "钢琴", None))
        self.checkBox28.setText(_translate("UI_TagSelector", "弦乐组", None))
        self.checkBox29.setText(_translate("UI_TagSelector", "管乐组", None))
        self.checkBox30.setText(_translate("UI_TagSelector", "室内乐", None))
        self.checkBox31.setText(_translate("UI_TagSelector", "电吉他", None))
        self.checkBox32.setText(_translate("UI_TagSelector", "口琴", None))
        self.checkBox33.setText(_translate("UI_TagSelector", "古筝", None))
        self.checkBox34.setText(_translate("UI_TagSelector", "二胡", None))
        self.checkBox35.setText(_translate("UI_TagSelector", "琵琶", None))
        self.checkBox36.setText(_translate("UI_TagSelector", "箫笛", None))

        self.btn_tagOK.setText(_translate("UI_TagSelector", "确定", None))
